version: "3.8"
services:
  frontend:
    build:
      context: "."
      dockerfile: Dockerfile
    container_name: "you-pt-fe"
    working_dir: "/usr/src/app"
    ports:
      - "3500:3000"
    volumes:
      - /usr/src/app/node_modules
      # 컨테이너밖: 컨테이너안
      - .:/usr/src/app
    command: ["npm", "run", "start"]
# services에 여러 개를 넣으면, 여러 컨테이너를 한번에 실행할 수 있다.

######### 실행 방법 #########

# 기본 설정 파일인 docker-compose.yml 실행 시.
# -d: 백그라운드 실행.
# docker-compose up -d

# 사용자 지정 설정파일 실행 시 -f 옵션
# docker-compose -f <파일명.yml> up -d
